#!/bin/sh
# vendor-licensing.sh: vendor the private licensing-core git dependency
# into ./vendor/ so the Docker build (Dockerfile.ent) never needs
# credentials for it.
#
# Why: the `ent` cargo feature pulls licensing-core from the private
# ShristiLabs/licensing repo (rev-pinned in the workspace Cargo.toml).
# Local cargo builds authenticate via your git credential helper; a
# Docker build has none.
#
# How: run `cargo vendor` on the HOST (where your credentials live) with
# the ent feature enabled, then keep only the licensing-core crate from
# its output. cargo vendor is the right tool because it REWRITES the
# crate's manifest into a standalone form -- the original inherits
# version/edition/license/authors from the licensing workspace root,
# which does not exist outside that repo and would fail to parse in a
# directory source. Finally the script writes the cargo
# source-replacement config that redirects the git pin to the vendored
# copy. Dockerfile.ent COPYs both into its builder stage.
#
# The config is generated (not committed) so the rev pin and the
# replacement key cannot drift apart. The key form matches what
# `cargo vendor` itself emits for rev-pinned git deps:
#   [source."git+<url>?rev=<rev>"] with git/rev fields and replace-with.
# The directory path is absolute, points at the PARENT of the crate
# (directory sources scan their subdirectories for crates, exactly like
# a cargo-vendor tree), and must match the builder's WORKDIR (/build in
# Dockerfile.ent).
#
# Requires: read access to github.com/ShristiLabs/licensing (any
# ShristiLabs member or an entitled customer with a token in their git
# credential helper).
set -eu

cd "$(dirname "$0")"

REPO_URL=https://github.com/ShristiLabs/licensing.git
# The pinned revision, read from the workspace manifest so this script
# and Cargo.lock cannot drift apart.
REV=$(sed -n 's/.*licensing.git", rev = "\([0-9a-f]*\)".*/\1/p' ../../Cargo.toml)
if [ -z "$REV" ]; then
    echo "vendor-licensing.sh: could not read the licensing-core rev from ../../Cargo.toml" >&2
    exit 1
fi

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

echo "cargo vendoring (ent features) in $(cd ../.. && pwd) ..."
(cd ../.. && CARGO_FEATURE_ENT=1 cargo vendor --versioned-dirs "$TMP/vendor") \
    >/dev/null

# Only the licensing-core crate -- the full vendor tree carries every
# crates.io dependency of the workspace, which the Docker build fetches
# normally from crates.io (public, no auth needed).
VENDORED=$(echo "$TMP"/vendor/licensing-core-*)
if [ ! -d "$VENDORED" ]; then
    echo "vendor-licensing.sh: cargo vendor produced no licensing-core crate" >&2
    exit 1
fi

rm -rf vendor
mkdir -p vendor
cp -R "$VENDORED" vendor/licensing-core

cat > vendor/cargo-vendor.toml <<EOF
# Generated by vendor-licensing.sh -- do not edit; re-run the script
# when the licensing-core rev pin in the workspace Cargo.toml changes.
# Consumed by Dockerfile.ent (copied to /build/.cargo/config.toml).
[source."git+$REPO_URL?rev=$REV"]
git = "$REPO_URL"
rev = "$REV"
replace-with = "dwara-vendored-licensing"

[source.dwara-vendored-licensing]
directory = "/build/third-party"
EOF

echo "vendored licensing-core $REV into ./vendor/licensing-core"
echo "next: docker compose up"
