[workspace]
resolver = "2"
members = [
    "crates/dwara-core",
    "crates/dwara-bin",
    "crates/dwara-admin",
    "crates/dwara-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.94"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "1", features = ["server", "http1"] }
hyper-util = { version = "0.1", features = ["tokio", "server", "server-graceful", "http1"] }
http-body-util = "0.1"
schemars = "1"
serde = { version = "1", features = ["derive"] }
serde_path_to_error = "0.1"
serde_yaml_ng = "0.10"
serde_json = "1"
async-trait = "0.1"
arc-swap = "1"
matchit = "0.9"
regex = "1"
notify = "8"

[profile.release]
lto = true
