apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dwara.fullname" . }}-controller-config
  namespace: {{ include "dwara.namespace" . }}
  labels:
    {{- include "dwara.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
data:
  {{- range $k, $v := .Values.controller.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
