#!/usr/bin/env python3
"""Build tools/config-studio/index.html.

Inlines the authoritative config JSON Schema (config-reference.json,
generated by `dwara schema`) and the vendored js-yaml parser into the
app template, producing a single-file, fully offline tool.

Run from anywhere:  python3 tools/config-studio/build.py

Re-run whenever config-reference.json changes (same cadence as the
committed schema diff check in CI).

Internal DW-### issue references are scrubbed from schema descriptions
at build time so end users never see them; the committed
config-reference.json itself is never modified.
"""

import json
import pathlib
import re

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[1]


def guard_inline(text: str) -> str:
    """Prevent an embedded script from terminating its <script> tag."""
    return text.replace("</script", "<\\/script").replace(
        "</SCRIPT", "<\\/SCRIPT"
    )


# Tracking-reference families that appear in upstream doc comments:
# the internal issue tracker (DW-###, DW-AI-###, pre-DW-###) and the
# enhancement-catalog IDs (SEC/CFG/AI/DP/REL/PERF/SCALE/USA/FEAT-##).
# Deliberately UPPERCASE-only so technical tokens survive: SHA-256,
# HTTP-01, TLS-ALPN-01, "N-1 or N+1" skew semantics, "2^(n-1)" math,
# region/model names.
TRACKING_RE = re.compile(
    r"\b(?:pre-)?(?:DW(?:-[A-Z]+)?|SEC|CFG|AI|DP|REL|PERF|SCALE|USA|FEAT)-\d{1,4}\b"
)


def strip_issue_refs(text: str) -> str:
    """Remove internal tracking references from help text.

    The upstream schema descriptions carry development references:
    issue IDs (DW-###, DW-AI-###), enhancement-catalog IDs (SEC-04,
    CFG-14, AI-01, ...), bare GitHub refs (#121), and "feature
    analysis 4.7" pointers. They are meaningless to operators, so the
    TOKENS are removed here (surrounding words like "(#124,
    termination mode only)" survive as "(termination mode only)") in
    the built artifact only.
    """
    t = TRACKING_RE.sub("", text)
    t = re.sub(r"#\d+\b", "", t)  # JSON pointers are "#/...", never "#<digits>"
    t = re.sub(r"feature\s+analysis\s+[\w.\-]+", "", t)
    # orphaned separators left behind by token removal
    t = re.sub(r"\s*/\s*(?=[,;:.])", "", t)
    t = re.sub(r"^\s*[,/;:]\s*", "", t)
    t = re.sub(r"\(\s*[,/;:]\s*", "(", t)
    t = re.sub(r"\(\s*,\s*", "(", t)
    t = re.sub(r"\(\s*,\s*\)", "()", t)
    t = re.sub(r"\(\s*\)", "", t)
    t = re.sub(r"\(\s+", "(", t)
    t = re.sub(r"\s+\)", ")", t)
    # sentence punctuation only: not paths (" ../x"), ports (" :8443"),
    # or ellipses -- the punctuation must be followed by space/end
    t = re.sub(r"\s+([,;:])(?=\s|$)", r"\1", t)
    t = re.sub(r"\s+\.(\s|$)", r".\1", t)
    t = re.sub(r"\s{2,}", " ", t)
    return t


def scrub(node) -> None:
    """Recursively scrub description strings in the parsed schema."""
    if isinstance(node, dict):
        for k, v in node.items():
            if k == "description" and isinstance(v, str):
                node[k] = strip_issue_refs(v)
            else:
                scrub(v)
    elif isinstance(node, list):
        for item in node:
            scrub(item)


def main() -> None:
    schema = json.loads((ROOT / "config-reference.json").read_text())
    scrub(schema)
    jsyaml = (HERE / "vendor" / "js-yaml.min.js").read_text()
    template = (HERE / "src" / "app.template.html").read_text()

    if "__SCHEMA_JSON__" not in template or "/*__JSYAML__*/" not in template:
        raise SystemExit("template is missing its build markers")

    # Pretty-print the schema inside the JSON script tag so the built
    # artifact remains inspectable; escape any literal </script>.
    pretty = json.dumps(schema, indent=1)
    out = template.replace("/*__JSYAML__*/", guard_inline(jsyaml), 1)
    out = out.replace("__SCHEMA_JSON__", guard_inline(pretty), 1)

    dest = HERE / "index.html"
    dest.write_text(out)
    print(f"wrote {dest} ({len(out) // 1024} KiB)")


if __name__ == "__main__":
    main()
