#!/usr/bin/env python3
"""Build tools/config-studio/index.html.

Inlines the authoritative config JSON Schema (config-reference.json,
generated by `dwara schema`) and the vendored js-yaml parser into the
app template, producing a single-file, fully offline tool.

Run from anywhere:  python3 tools/config-studio/build.py

Re-run whenever config-reference.json changes (same cadence as the
committed schema diff check in CI).

Internal DW-### issue references are scrubbed from schema descriptions
at build time so end users never see them; the committed
config-reference.json itself is never modified.
"""

import json
import pathlib
import re

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[1]


def guard_inline(text: str) -> str:
    """Prevent an embedded script from terminating its <script> tag."""
    return text.replace("</script", "<\\/script").replace(
        "</SCRIPT", "<\\/SCRIPT"
    )


def strip_issue_refs(text: str) -> str:
    """Remove internal DW-### tracking references from help text.

    The upstream schema descriptions carry development tracking IDs
    (DW-019, DW-045, "feature analysis 4.7", ...). They are meaningless
    to operators using this tool, so they are scrubbed here, in the
    built artifact only.
    """
    t = re.sub(r"\((?:feature analysis )?DW-\d+(?:, [^()]*)?\)", "", text)
    t = re.sub(r"\bDW-\d+\b", "", t)
    t = re.sub(r"\(\s+", "(", t)
    t = re.sub(r"\s+\)", ")", t)
    t = re.sub(r"\(\)", "", t)
    t = re.sub(r"\s+([.,;:])", r"\1", t)
    t = re.sub(r"  +", " ", t)
    return t


def scrub(node) -> None:
    """Recursively scrub description strings in the parsed schema."""
    if isinstance(node, dict):
        for k, v in node.items():
            if k == "description" and isinstance(v, str):
                node[k] = strip_issue_refs(v)
            else:
                scrub(v)
    elif isinstance(node, list):
        for item in node:
            scrub(item)


def main() -> None:
    schema = json.loads((ROOT / "config-reference.json").read_text())
    scrub(schema)
    jsyaml = (HERE / "vendor" / "js-yaml.min.js").read_text()
    template = (HERE / "src" / "app.template.html").read_text()

    if "__SCHEMA_JSON__" not in template or "/*__JSYAML__*/" not in template:
        raise SystemExit("template is missing its build markers")

    # Pretty-print the schema inside the JSON script tag so the built
    # artifact remains inspectable; escape any literal </script>.
    pretty = json.dumps(schema, indent=1)
    out = template.replace("/*__JSYAML__*/", guard_inline(jsyaml), 1)
    out = out.replace("__SCHEMA_JSON__", guard_inline(pretty), 1)

    dest = HERE / "index.html"
    dest.write_text(out)
    print(f"wrote {dest} ({len(out) // 1024} KiB)")


if __name__ == "__main__":
    main()
