//! dwara-cli (DW-022): the operator command line.
//!
//! Subcommands:
//!
//! - `run [ARGS]...` — run the gateway SERVER: spawns the `dwara`
//!   binary with the given arguments (environment passes through;
//!   `DWARA_CONFIG`, `DWARA_BIND`, ... control it). Documented v1
//!   shape: the CLI does not embed the server; it requires the `dwara`
//!   binary on PATH and propagates its exit status.
//! - `validate <file>` — parse + validate + compile-dry-run; prints
//!   EVERY issue; exit 1 on any (0 on success, printing the route
//!   count).
//! - `fmt <file>` — normalize the file in place (stable field order,
//!   defaulted-empty collections dropped). Prints nothing on success.
//! - `diff <a> <b>` — compile both configs and print route/upstream/
//!   consumer deltas (`+ kind name` / `- kind name`).
//! - `lint <file>` — advisory rules BEYOND validation; exit 2 on
//!   warnings (distinct from validation's 1; see the lib docs), 1 if
//!   the file cannot be parsed/validated.
//! - `schema` — print the JSON Schema of the gateway config (DW-026,
//!   feature analysis 13.5) to STDOUT, pretty-printed. The committed
//!   `config-reference.json` (repo root) is generated by this subcommand; CI
//!   regenerates and diffs so the reference cannot drift from code.
//! - `import openapi <spec> [--output dwara.yaml]` — read an OpenAPI
//!   3.x spec (YAML or JSON) and generate a Dwara config with routes
//!   derived from the spec's paths and methods (DW-047).
//! - `upgrade [--pid <N> | --pid-file <path>]` — send SIGUSR2 to a
//!   running gateway to trigger a zero-downtime binary upgrade (DW-049).
//!   The PID is read from `--pid` or from the PID file (`--pid-file` or
//!   the `DWARA_PID_FILE` env var). The gateway must have been started
//!   with `DWARA_PID_FILE` set (or the PID supplied explicitly).

use clap::{Parser, Subcommand};

/// dwara gateway operator CLI.
#[derive(Parser)]
#[command(name = "dwara-cli", version, about = "dwara gateway operator CLI")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Run the gateway server (spawns the `dwara` binary).
    Run {
        /// Arguments passed verbatim to the dwara binary.
        #[arg(trailing_var_arg = true, allow_hyphen_values = true)]
        args: Vec<String>,
    },
    /// Validate a config file; exit 1 on any issue.
    Validate {
        /// Path to the gateway YAML config.
        file: String,
    },
    /// Normalize a config file in place.
    Fmt {
        /// Path to the gateway YAML config (rewritten).
        file: String,
    },
    /// Show route/upstream/consumer deltas between two configs.
    Diff {
        /// Baseline config.
        a: String,
        /// Changed config.
        b: String,
    },
    /// Advisory lint rules; exit 2 on warnings.
    Lint {
        /// Path to the gateway YAML config.
        file: String,
    },
    /// Print the JSON Schema of the gateway config.
    Schema,
    /// Import an external spec and generate a Dwara config.
    Import {
        #[command(subcommand)]
        kind: ImportKind,
    },
    /// Trigger a zero-downtime binary upgrade (sends SIGUSR2).
    Upgrade {
        /// PID of the running gateway to signal. If omitted, the PID is
        /// read from `--pid-file` (or the `DWARA_PID_FILE` env var).
        #[arg(long)]
        pid: Option<u32>,
        /// Path to the gateway's PID file. Defaults to `DWARA_PID_FILE`.
        #[arg(long)]
        pid_file: Option<String>,
    },
}

#[derive(Subcommand)]
enum ImportKind {
    /// Import an OpenAPI 3.x spec (YAML or JSON) and generate a Dwara config.
    Openapi {
        /// Path to the OpenAPI spec (.yaml, .yml, or .json).
        spec: String,
        /// Output path for the generated Dwara config (default: dwara.yaml).
        #[arg(long, default_value = "dwara.yaml")]
        output: String,
    },
}

fn read(path: &str) -> Result<String, String> {
    std::fs::read_to_string(path).map_err(|e| format!("cannot read {path}: {e}"))
}

/// Write `contents` to `path` atomically: named temp file in the same
/// directory (same filesystem, so the rename is atomic), fsync, rename
/// over the destination. A crash mid-`fmt` leaves the operator's config
/// as either the old or the new document, never a truncated one.
fn write_atomic(path: &str, contents: &str) -> Result<(), String> {
    let dir = std::path::Path::new(path)
        .parent()
        .unwrap_or(std::path::Path::new("."));
    let mut tmp = tempfile::NamedTempFile::new_in(dir)
        .map_err(|e| format!("cannot create temp file near {path}: {e}"))?;
    use std::io::Write as _;
    tmp.write_all(contents.as_bytes())
        .and_then(|_| tmp.flush())
        .map_err(|e| format!("cannot write temp file for {path}: {e}"))?;
    tmp.reopen()
        .and_then(|f| f.sync_all())
        .map_err(|e| format!("cannot fsync temp file for {path}: {e}"))?;
    tmp.persist(path)
        .map_err(|e| format!("cannot replace {path}: {e}"))?;
    Ok(())
}

fn main() {
    let cli = Cli::parse();
    let code = match cli.command {
        Command::Run { args } => run_server(&args),
        // The schema is deterministic for a given build: schemars walks
        // the serde model, so the output bytes are stable (CI regenerates
        // and diffs the committed reference against this stream).
        Command::Schema => {
            let schema = dwara_core::config::json_schema();
            match serde_json::to_string_pretty(&schema) {
                Ok(json) => {
                    println!("{json}");
                    0
                }
                Err(e) => {
                    eprintln!("cannot serialize schema: {e}");
                    1
                }
            }
        }
        Command::Validate { file } => match read(&file) {
            Err(e) => {
                eprintln!("{e}");
                1
            }
            Ok(text) => match dwara_cli::validate_config_text(&text) {
                dwara_cli::ValidateOutcome::Valid { routes } => {
                    println!("ok: {routes} routes");
                    0
                }
                dwara_cli::ValidateOutcome::Invalid(issues) => {
                    for i in issues {
                        eprintln!("{i}");
                    }
                    1
                }
            },
        },
        Command::Fmt { file } => match read(&file) {
            Err(e) => {
                eprintln!("{e}");
                1
            }
            Ok(text) => match dwara_cli::format_config_text(&text) {
                Ok(normalized) => match write_atomic(&file, &normalized) {
                    Ok(()) => 0,
                    Err(e) => {
                        eprintln!("{e}");
                        1
                    }
                },
                Err(e) => {
                    eprintln!("{e}");
                    1
                }
            },
        },
        Command::Diff { a, b } => {
            let both = read(&a).and_then(|ta| read(&b).map(|tb| (ta, tb)));
            match both {
                Err(e) => {
                    eprintln!("{e}");
                    1
                }
                Ok((ta, tb)) => match dwara_cli::diff_configs(&ta, &tb) {
                    Ok(out) => {
                        print!("{out}");
                        0
                    }
                    Err(e) => {
                        eprintln!("{e}");
                        1
                    }
                },
            }
        }
        Command::Lint { file } => match read(&file) {
            Err(e) => {
                eprintln!("{e}");
                1
            }
            Ok(text) => match dwara_cli::validate_config_text(&text) {
                dwara_cli::ValidateOutcome::Invalid(issues) => {
                    for i in issues {
                        eprintln!("{i}");
                    }
                    eprintln!("config is invalid; fix validation before linting");
                    1
                }
                dwara_cli::ValidateOutcome::Valid { .. } => {
                    let gateway =
                        dwara_core::config::parse_gateway(&text).expect("validated above");
                    let warnings = dwara_cli::lint_config(&gateway);
                    for w in &warnings {
                        eprintln!("warning: {w}");
                    }
                    if warnings.is_empty() {
                        0
                    } else {
                        eprintln!("{} lint warning(s)", warnings.len());
                        2
                    }
                }
            },
        },
        Command::Import { kind } => match kind {
            ImportKind::Openapi { spec, output } => match read(&spec) {
                Err(e) => {
                    eprintln!("{e}");
                    1
                }
                Ok(text) => {
                    let is_json = dwara_cli::import::is_json_spec(&text) || spec.ends_with(".json");
                    match dwara_cli::import::import_openapi(&text, is_json) {
                        Ok(result) => match write_atomic(&output, &result.yaml) {
                            Ok(()) => {
                                println!(
                                    "imported {} routes from {} -> {}",
                                    result.route_count, spec, output
                                );
                                0
                            }
                            Err(e) => {
                                eprintln!("{e}");
                                1
                            }
                        },
                        Err(e) => {
                            eprintln!("{e}");
                            1
                        }
                    }
                }
            },
        },
        Command::Upgrade { pid, pid_file } => run_upgrade(pid, pid_file),
    };
    std::process::exit(code);
}

/// Spawn the `dwara` server binary with argument passthrough. The
/// environment passes through unchanged (DWARA_CONFIG etc.); the
/// CLI stays a thin operator front-end, not a second server host.
fn run_server(args: &[String]) -> i32 {
    let mut cmd = std::process::Command::new("dwara");
    cmd.args(args);
    match cmd.status() {
        Ok(status) => status.code().unwrap_or(1),
        Err(e) => {
            eprintln!("cannot spawn the dwara binary: {e} (is it installed and on PATH?)");
            1
        }
    }
}

/// DW-049: send SIGUSR2 to a running gateway to trigger a zero-downtime
/// binary upgrade. The PID is resolved from `--pid`, else the PID file
/// (`--pid-file` or `DWARA_PID_FILE`). The gateway spawns a new copy of
/// itself (SO_REUSEPORT hand-off), drains, and exits; the new process
/// takes over with no refused connections. This command only DELIVERS the
/// signal — the hand-off is asynchronous; watch the gateway logs or the
/// PID file to confirm the new process is live.
fn run_upgrade(pid: Option<u32>, pid_file: Option<String>) -> i32 {
    let pid = match pid {
        Some(p) => p,
        None => {
            let path = pid_file
                .or_else(|| std::env::var("DWARA_PID_FILE").ok())
                .filter(|s| !s.is_empty());
            let Some(path) = path else {
                eprintln!(
                    "upgrade: no PID given. Pass --pid <N> or --pid-file <path>, \
                     or start the gateway with DWARA_PID_FILE set."
                );
                return 1;
            };
            let text = match std::fs::read_to_string(&path) {
                Ok(t) => t,
                Err(e) => {
                    eprintln!("upgrade: cannot read PID file {path}: {e}");
                    return 1;
                }
            };
            match text.trim().parse::<u32>() {
                Ok(p) => p,
                Err(_) => {
                    eprintln!("upgrade: PID file {path} does not contain a valid PID");
                    return 1;
                }
            }
        }
    };
    // libc::kill is the portable Unix primitive (no shell-out to `kill`).
    // SIGUSR2 (12) is the upgrade trigger the gateway's signal handler
    // listens for alongside SIGHUP/SIGTERM/SIGINT.
    let rc = unsafe { libc::kill(pid as i32, libc::SIGUSR2) };
    if rc == 0 {
        println!(
            "upgrade: SIGUSR2 sent to PID {pid}; the gateway will spawn a new \
             process, drain, and exit. Watch the logs to confirm the hand-off."
        );
        0
    } else {
        let err = std::io::Error::last_os_error();
        eprintln!("upgrade: failed to signal PID {pid}: {err}");
        1
    }
}
