//! dwara-cli (DW-022): the operator command line.
//!
//! Subcommands:
//!
//! - `run [ARGS]...` — run the gateway SERVER: spawns the `dwara`
//!   binary with the given arguments (environment passes through;
//!   `DWARA_CONFIG`, `DWARA_BIND`, ... control it). Documented v1
//!   shape: the CLI does not embed the server; it requires the `dwara`
//!   binary on PATH and propagates its exit status.
//! - `validate <file>` — parse + validate + compile-dry-run; prints
//!   EVERY issue; exit 1 on any (0 on success, printing the route
//!   count).
//! - `fmt <file>` — normalize the file in place (stable field order,
//!   defaulted-empty collections dropped). Prints nothing on success.
//! - `diff <a> <b>` — compile both configs and print route/upstream/
//!   consumer deltas (`+ kind name` / `- kind name`).
//! - `lint <file>` — advisory rules BEYOND validation; exit 2 on
//!   warnings (distinct from validation's 1; see the lib docs), 1 if
//!   the file cannot be parsed/validated.
//! - `schema` — print the JSON Schema of the gateway config (DW-026,
//!   feature analysis 13.5) to STDOUT, pretty-printed. The committed
//!   `config-reference.json` (repo root) is generated by this subcommand; CI
//!   regenerates and diffs so the reference cannot drift from code.
//! - `import openapi <spec> [--output dwara.yaml]` — read an OpenAPI
//!   3.x spec (YAML or JSON) and generate a Dwara config with routes
//!   derived from the spec's paths and methods (DW-047).
//! - `import nginx <config> [--output dwara.yaml]` — read an NGINX
//!   config and generate a Dwara config with routes derived from the
//!   NGINX location blocks (DW-065). Unsupported constructs are
//!   reported as warnings in the generated config.
//! - `upgrade [--pid <N> | --pid-file <path>]` — send SIGUSR2 to a
//!   running gateway to trigger a zero-downtime binary upgrade (DW-049).
//!   The PID is read from `--pid` or from the PID file (`--pid-file` or
//!   the `DWARA_PID_FILE` env var). The gateway must have been started
//!   with `DWARA_PID_FILE` set (or the PID supplied explicitly).

use clap::{Parser, Subcommand};

/// dwara gateway operator CLI.
#[derive(Parser)]
#[command(name = "dwara-cli", version, about = "dwara gateway operator CLI")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Run the gateway server (spawns the `dwara` binary).
    Run {
        /// Arguments passed verbatim to the dwara binary.
        #[arg(trailing_var_arg = true, allow_hyphen_values = true)]
        args: Vec<String>,
    },
    /// Validate a config file; exit 1 on any issue.
    Validate {
        /// Path to the gateway YAML config.
        file: String,
        /// Apply the named profile (CFG-01, #180) before validating.
        /// Loads `<profiles_dir>/<profile>.yaml` when `profiles_dir` is
        /// set, else the inline `profile_overrides` entry. Also resolves
        /// `includes:` directives.
        #[arg(long)]
        profile: Option<String>,
    },
    /// Normalize a config file in place.
    Fmt {
        /// Path to the gateway YAML config (rewritten).
        file: String,
    },
    /// Show route/upstream/consumer deltas between two configs.
    Diff {
        /// Baseline config.
        a: String,
        /// Changed config.
        b: String,
    },
    /// Advisory lint rules; exit 2 on warnings.
    Lint {
        /// Path to the gateway YAML config.
        file: String,
        /// Apply the named profile (CFG-01, #180) before linting.
        #[arg(long)]
        profile: Option<String>,
    },
    /// Print the JSON Schema of the gateway config.
    Schema,
    /// Import an external spec and generate a Dwara config.
    Import {
        #[command(subcommand)]
        kind: ImportKind,
    },
    /// Terraform-compatible state tool (DW-065): export/plan/apply
    /// gateway config as Terraform state + HCL over the admin API.
    Tf {
        #[command(subcommand)]
        kind: TfKind,
    },
    /// Trigger a zero-downtime binary upgrade (sends SIGUSR2).
    Upgrade {
        /// PID of the running gateway to signal. If omitted, the PID is
        /// read from `--pid-file` (or the `DWARA_PID_FILE` env var).
        #[arg(long)]
        pid: Option<u32>,
        /// Path to the gateway's PID file. Defaults to `DWARA_PID_FILE`.
        #[arg(long)]
        pid_file: Option<String>,
    },
    /// Plugin scaffolding and management (DW-057).
    Plugin {
        #[command(subcommand)]
        kind: PluginKind,
    },
    /// Replay time-travel debugging (DW-102): re-run the gateway's
    /// decision path for recorded requests against a candidate config
    /// and emit a per-request diff. Exit 0 if no diffs, 1 if diffs
    /// found (useful as a CI gate).
    Replay {
        /// Path to a recording JSON file (exported from analytics or
        /// authored by hand): `{baseline_config, requests[]}`.
        #[arg(long)]
        recording: Option<String>,
        /// Read requests from the analytics store directly (requires
        /// `--analytics-db` and `--baseline`). The lower bound
        /// timestamp (Unix ms).
        #[arg(long)]
        from: Option<i64>,
        /// The upper bound timestamp (Unix ms) for `--from`.
        #[arg(long, requires = "from")]
        to: Option<i64>,
        /// Path to the analytics SQLite database (for `--from/--to`).
        #[arg(long)]
        analytics_db: Option<String>,
        /// Path to the baseline config YAML (for `--from/--to`; the
        /// config the requests were captured under).
        #[arg(long)]
        baseline: Option<String>,
        /// Path to the candidate config YAML (the new config to test).
        #[arg(long)]
        config: String,
    },
    /// Kubernetes Gateway API tools (DW-064). Feature-gated behind `k8s`.
    K8s {
        #[command(subcommand)]
        kind: K8sKind,
    },
    /// Show the running gateway's status (generation, health, breakers).
    Status {
        /// Admin API base URL (e.g. http://127.0.0.1:2019). Defaults to
        /// `DWARA_ADMIN` or http://127.0.0.1:2019.
        #[arg(long)]
        admin: Option<String>,
    },
    /// Live view of upstream load-balancer state and shedding. Refreshes
    /// until interrupted (Ctrl-C).
    Top {
        /// Admin API base URL (e.g. http://127.0.0.1:2019). Defaults to
        /// `DWARA_ADMIN` or http://127.0.0.1:2019.
        #[arg(long)]
        admin: Option<String>,
        /// Refresh interval in milliseconds (default 1000).
        #[arg(long, default_value_t = 1000)]
        interval: u64,
    },
    /// Generate shell completion scripts (bash/zsh/fish/PowerShell).
    Completions {
        /// The target shell.
        shell: CompletionShell,
    },
}

/// Supported shells for `dwara completions` (USA-02, #179).
#[derive(clap::ValueEnum, Clone, Debug)]
enum CompletionShell {
    Bash,
    Zsh,
    Fish,
    Powershell,
}

/// Subcommands of `dwara k8s` (DW-064).
#[derive(Subcommand)]
enum K8sKind {
    /// Generate the upstream Gateway API conformance report YAML based
    /// on the features the translator supports. This is the artifact an
    /// operator submits to be listed on k8s.io.
    ConformanceReport {
        /// Output path for the conformance report YAML (default: stdout).
        #[arg(long, short = 'o')]
        output: Option<String>,
    },
}

#[derive(Subcommand)]
enum PluginKind {
    /// Scaffold a new proxy-wasm plugin project (Rust -> wasm32-wasip1).
    New {
        /// The plugin name (used for the crate name and directory).
        name: String,
        /// The parent directory; the scaffold is created in `<dir>/<name>/`.
        /// Defaults to the current directory.
        #[arg(long, short = 'o', default_value = ".")]
        dir: String,
    },
    /// SCALE-12 (#192): Search the plugin registry for available plugins.
    Search {
        /// The registry URL to search. If absent, uses the
        /// `DWARA_PLUGIN_REGISTRY` env var or the default registry.
        #[arg(long)]
        registry: Option<String>,
        /// Optional search query (substring match on plugin names).
        query: Option<String>,
    },
    /// SCALE-12 (#192): Download and verify a plugin from the registry.
    Install {
        /// The plugin name to install.
        name: String,
        /// The registry URL to install from. If absent, uses the
        /// `DWARA_PLUGIN_REGISTRY` env var or the default registry.
        #[arg(long)]
        registry: Option<String>,
        /// The expected SHA-256 digest (hex). If absent, the digest is
        /// fetched from the registry manifest.
        #[arg(long)]
        digest: Option<String>,
        /// Output directory for the downloaded .wasm file.
        #[arg(long, short = 'o', default_value = ".")]
        dir: String,
    },
}

#[derive(Subcommand)]
enum ImportKind {
    /// Import an OpenAPI 3.x spec (YAML or JSON) and generate a Dwara config.
    Openapi {
        /// Path to the OpenAPI spec (.yaml, .yml, or .json).
        spec: String,
        /// Output path for the generated Dwara config (default: dwara.yaml).
        #[arg(long, default_value = "dwara.yaml")]
        output: String,
    },
    /// Import an NGINX config and generate a Dwara config (DW-065).
    Nginx {
        /// Path to the NGINX config file.
        config: String,
        /// Output path for the generated Dwara config (default: dwara.yaml).
        #[arg(long, default_value = "dwara.yaml")]
        output: String,
    },
    /// Import a Kong declarative config (decK YAML or JSON) and generate
    /// a Dwara config (DW-065).
    Kong {
        /// Path to the Kong config file (.yaml, .yml, or .json).
        config: String,
        /// Output path for the generated Dwara config (default: dwara.yaml).
        #[arg(long, default_value = "dwara.yaml")]
        output: String,
    },
    /// Import an Envoy static config (YAML) and generate a Dwara config
    /// (DW-065).
    Envoy {
        /// Path to the Envoy config file (.yaml or .yml).
        config: String,
        /// Output path for the generated Dwara config (default: dwara.yaml).
        #[arg(long, default_value = "dwara.yaml")]
        output: String,
    },
}

/// Subcommands of `dwara tf` (DW-065).
#[derive(Subcommand)]
enum TfKind {
    /// Export the running gateway's config as Terraform state + HCL
    /// (state import: bring a running gateway under management).
    Export {
        /// Admin API base URL (e.g. http://127.0.0.1:2019).
        #[arg(long)]
        admin: String,
        /// Path to the CA bundle for mTLS (follow-up; dev admin is plaintext).
        #[arg(long)]
        ca: Option<String>,
        /// Path to the client certificate for mTLS (follow-up).
        #[arg(long)]
        client_cert: Option<String>,
        /// Path to the client key for mTLS (follow-up).
        #[arg(long)]
        client_key: Option<String>,
        /// Output path for the tfstate JSON file (default: dwara.tfstate).
        #[arg(long, default_value = "dwara.tfstate")]
        out_state: String,
        /// Output path for the HCL file (default: dwara.tf).
        #[arg(long, default_value = "dwara.tf")]
        out_hcl: String,
    },
    /// Compare local tfstate against the running gateway and print the
    /// diff (plan). Exit 0 if no diff, 1 if diff.
    Plan {
        /// Admin API base URL (e.g. http://127.0.0.1:2019).
        #[arg(long)]
        admin: String,
        /// Path to the local tfstate JSON file.
        #[arg(long)]
        state: String,
        /// Path to the CA bundle for mTLS (follow-up; dev admin is plaintext).
        #[arg(long)]
        ca: Option<String>,
    },
    /// Push the desired config to the gateway (apply). If `--config` is
    /// given, use that YAML; otherwise derive the desired YAML from the
    /// tfstate. Refreshes state from the gateway response.
    Apply {
        /// Admin API base URL (e.g. http://127.0.0.1:2019).
        #[arg(long)]
        admin: String,
        /// Path to the local tfstate JSON file.
        #[arg(long)]
        state: String,
        /// Optional path to a desired config YAML file (overrides state).
        #[arg(long)]
        config: Option<String>,
        /// Path to the CA bundle for mTLS (follow-up; dev admin is plaintext).
        #[arg(long)]
        ca: Option<String>,
    },
    /// SCALE-12 (#193): Apply the desired state to the gateway using
    /// per-entity CRUD operations (true provider behavior). Each
    /// resource is managed independently via POST/PUT/DELETE against
    /// the admin API's entity CRUD endpoints, instead of full-document
    /// PATCH /config.
    ApplyCrud {
        /// Admin API base URL (e.g. http://127.0.0.1:2019).
        #[arg(long)]
        admin: String,
        /// Path to the local tfstate JSON file.
        #[arg(long)]
        state: String,
        /// Path to the CA bundle for mTLS (follow-up; dev admin is plaintext).
        #[arg(long)]
        ca: Option<String>,
    },
}

fn read(path: &str) -> Result<String, String> {
    std::fs::read_to_string(path).map_err(|e| format!("cannot read {path}: {e}"))
}

/// Write `contents` to `path` atomically: named temp file in the same
/// directory (same filesystem, so the rename is atomic), fsync, rename
/// over the destination. A crash mid-`fmt` leaves the operator's config
/// as either the old or the new document, never a truncated one.
fn write_atomic(path: &str, contents: &str) -> Result<(), String> {
    let dir = std::path::Path::new(path)
        .parent()
        .unwrap_or(std::path::Path::new("."));
    let mut tmp = tempfile::NamedTempFile::new_in(dir)
        .map_err(|e| format!("cannot create temp file near {path}: {e}"))?;
    use std::io::Write as _;
    tmp.write_all(contents.as_bytes())
        .and_then(|_| tmp.flush())
        .map_err(|e| format!("cannot write temp file for {path}: {e}"))?;
    tmp.reopen()
        .and_then(|f| f.sync_all())
        .map_err(|e| format!("cannot fsync temp file for {path}: {e}"))?;
    tmp.persist(path)
        .map_err(|e| format!("cannot replace {path}: {e}"))?;
    Ok(())
}

fn main() {
    let cli = Cli::parse();
    let code = match cli.command {
        Command::Run { args } => run_server(&args),
        // The schema is deterministic for a given build: schemars walks
        // the serde model, so the output bytes are stable (CI regenerates
        // and diffs the committed reference against this stream).
        Command::Schema => {
            let schema = dwara_core::config::json_schema();
            match serde_json::to_string_pretty(&schema) {
                Ok(json) => {
                    println!("{json}");
                    0
                }
                Err(e) => {
                    eprintln!("cannot serialize schema: {e}");
                    1
                }
            }
        }
        Command::Validate { file, profile } => match read(&file) {
            Err(e) => {
                eprintln!("{e}");
                1
            }
            Ok(text) => {
                // CFG-01 (#180): resolve includes + profile before
                // validating. The base_dir is the config file's parent.
                let base_dir = std::path::Path::new(&file)
                    .parent()
                    .unwrap_or(std::path::Path::new("."))
                    .to_path_buf();
                match dwara_core::config::includes::preprocess(&text, &base_dir, profile.as_deref())
                {
                    Err(e) => {
                        eprintln!("{e}");
                        1
                    }
                    Ok(text) => match dwara_cli::validate_config_text(&text) {
                        dwara_cli::ValidateOutcome::Valid { routes } => {
                            println!("ok: {routes} routes");
                            0
                        }
                        dwara_cli::ValidateOutcome::Invalid(issues) => {
                            for i in issues {
                                eprintln!("{i}");
                            }
                            1
                        }
                    },
                }
            }
        },
        Command::Fmt { file } => match read(&file) {
            Err(e) => {
                eprintln!("{e}");
                1
            }
            Ok(text) => match dwara_cli::format_config_text(&text) {
                Ok(normalized) => match write_atomic(&file, &normalized) {
                    Ok(()) => 0,
                    Err(e) => {
                        eprintln!("{e}");
                        1
                    }
                },
                Err(e) => {
                    eprintln!("{e}");
                    1
                }
            },
        },
        Command::Diff { a, b } => {
            let both = read(&a).and_then(|ta| read(&b).map(|tb| (ta, tb)));
            match both {
                Err(e) => {
                    eprintln!("{e}");
                    1
                }
                Ok((ta, tb)) => match dwara_cli::diff_configs(&ta, &tb) {
                    Ok(out) => {
                        print!("{out}");
                        0
                    }
                    Err(e) => {
                        eprintln!("{e}");
                        1
                    }
                },
            }
        }
        Command::Lint { file, profile } => match read(&file) {
            Err(e) => {
                eprintln!("{e}");
                1
            }
            Ok(text) => {
                // CFG-01 (#180): resolve includes + profile before linting.
                let base_dir = std::path::Path::new(&file)
                    .parent()
                    .unwrap_or(std::path::Path::new("."))
                    .to_path_buf();
                match dwara_core::config::includes::preprocess(&text, &base_dir, profile.as_deref())
                {
                    Err(e) => {
                        eprintln!("{e}");
                        1
                    }
                    Ok(text) => match dwara_cli::validate_config_text(&text) {
                        dwara_cli::ValidateOutcome::Invalid(issues) => {
                            for i in issues {
                                eprintln!("{i}");
                            }
                            eprintln!("config is invalid; fix validation before linting");
                            1
                        }
                        dwara_cli::ValidateOutcome::Valid { .. } => {
                            let gateway =
                                dwara_core::config::parse_gateway(&text).expect("validated above");
                            let warnings = dwara_cli::lint_config(&gateway);
                            for w in &warnings {
                                eprintln!("warning: {w}");
                            }
                            if warnings.is_empty() {
                                0
                            } else {
                                eprintln!("{} lint warning(s)", warnings.len());
                                2
                            }
                        }
                    },
                }
            }
        },
        Command::Import { kind } => match kind {
            ImportKind::Openapi { spec, output } => match read(&spec) {
                Err(e) => {
                    eprintln!("{e}");
                    1
                }
                Ok(text) => {
                    let is_json = dwara_cli::import::is_json_spec(&text) || spec.ends_with(".json");
                    match dwara_cli::import::import_openapi(&text, is_json) {
                        Ok(result) => match write_atomic(&output, &result.yaml) {
                            Ok(()) => {
                                println!(
                                    "imported {} routes from {} -> {}",
                                    result.route_count, spec, output
                                );
                                0
                            }
                            Err(e) => {
                                eprintln!("{e}");
                                1
                            }
                        },
                        Err(e) => {
                            eprintln!("{e}");
                            1
                        }
                    }
                }
            },
            ImportKind::Nginx { config, output } => match read(&config) {
                Err(e) => {
                    eprintln!("{e}");
                    1
                }
                Ok(text) => match dwara_cli::import_nginx::import_nginx(&text) {
                    Ok(result) => match write_atomic(&output, &result.yaml) {
                        Ok(()) => {
                            println!(
                                "imported {} routes from {} -> {}",
                                result.route_count, config, output
                            );
                            0
                        }
                        Err(e) => {
                            eprintln!("{e}");
                            1
                        }
                    },
                    Err(e) => {
                        eprintln!("{e}");
                        1
                    }
                },
            },
            ImportKind::Kong { config, output } => match read(&config) {
                Err(e) => {
                    eprintln!("{e}");
                    1
                }
                Ok(text) => {
                    let is_json =
                        dwara_cli::import::is_json_spec(&text) || config.ends_with(".json");
                    match dwara_cli::import_kong::import_kong(&text, is_json) {
                        Ok(result) => match write_atomic(&output, &result.yaml) {
                            Ok(()) => {
                                println!(
                                    "imported {} routes from {} -> {}",
                                    result.route_count, config, output
                                );
                                0
                            }
                            Err(e) => {
                                eprintln!("{e}");
                                1
                            }
                        },
                        Err(e) => {
                            eprintln!("{e}");
                            1
                        }
                    }
                }
            },
            ImportKind::Envoy { config, output } => match read(&config) {
                Err(e) => {
                    eprintln!("{e}");
                    1
                }
                Ok(text) => match dwara_cli::import_envoy::import_envoy(&text) {
                    Ok(result) => match write_atomic(&output, &result.yaml) {
                        Ok(()) => {
                            println!(
                                "imported {} routes from {} -> {}",
                                result.route_count, config, output
                            );
                            0
                        }
                        Err(e) => {
                            eprintln!("{e}");
                            1
                        }
                    },
                    Err(e) => {
                        eprintln!("{e}");
                        1
                    }
                },
            },
        },
        Command::Tf { kind } => run_tf(kind),
        Command::Upgrade { pid, pid_file } => run_upgrade(pid, pid_file),
        Command::Plugin { kind } => match kind {
            PluginKind::New { name, dir } => {
                match dwara_cli::plugin_scaffold::scaffold(&name, &dir) {
                    Ok(result) => {
                        println!(
                            "created plugin '{}' in {} ({} files)",
                            result.name,
                            result.dir,
                            result.files.len()
                        );
                        println!();
                        println!("next steps:");
                        println!("  cd {}", result.dir);
                        println!("  rustup target add wasm32-wasip1");
                        println!("  cargo build --release --target wasm32-wasip1");
                        println!("  dwara run --config dwara.yaml");
                        0
                    }
                    Err(e) => {
                        eprintln!("plugin new: {e}");
                        1
                    }
                }
            }
            PluginKind::Search { registry, query } => {
                match dwara_cli::plugin_registry::search(registry.as_deref(), query.as_deref()) {
                    Ok(output) => {
                        println!("{output}");
                        0
                    }
                    Err(e) => {
                        eprintln!("plugin search: {e}");
                        1
                    }
                }
            }
            PluginKind::Install {
                name,
                registry,
                digest,
                dir,
            } => {
                match dwara_cli::plugin_registry::install(
                    &name,
                    registry.as_deref(),
                    digest.as_deref(),
                    &dir,
                ) {
                    Ok(result) => {
                        println!(
                            "installed plugin '{}' -> {} (digest: {})",
                            result.name, result.path, result.digest
                        );
                        0
                    }
                    Err(e) => {
                        eprintln!("plugin install: {e}");
                        1
                    }
                }
            }
        },
        Command::K8s { kind } => match kind {
            K8sKind::ConformanceReport { output } => run_conformance_report(output),
        },
        Command::Status { admin } => run_status(admin),
        Command::Top { admin, interval } => run_top(admin, interval),
        Command::Completions { shell } => run_completions(shell),
        Command::Replay {
            recording,
            from,
            to,
            analytics_db,
            baseline,
            config,
        } => run_replay_cmd(recording, from, to, analytics_db, baseline, config),
    };
    std::process::exit(code);
}

/// Spawn the `dwara` server binary with argument passthrough. The
/// environment passes through unchanged (DWARA_CONFIG etc.); the
/// CLI stays a thin operator front-end, not a second server host.
fn run_server(args: &[String]) -> i32 {
    let mut cmd = std::process::Command::new("dwara");
    cmd.args(args);
    match cmd.status() {
        Ok(status) => status.code().unwrap_or(1),
        Err(e) => {
            eprintln!("cannot spawn the dwara binary: {e} (is it installed and on PATH?)");
            1
        }
    }
}

/// DW-049: send SIGUSR2 to a running gateway to trigger a zero-downtime
/// binary upgrade. The PID is resolved from `--pid`, else the PID file
/// (`--pid-file` or `DWARA_PID_FILE`). The gateway spawns a new copy of
/// itself (SO_REUSEPORT hand-off), drains, and exits; the new process
/// takes over with no refused connections. This command only DELIVERS the
/// signal — the hand-off is asynchronous; watch the gateway logs or the
/// PID file to confirm the new process is live.
fn run_upgrade(pid: Option<u32>, pid_file: Option<String>) -> i32 {
    let pid = match pid {
        Some(p) => p,
        None => {
            let path = pid_file
                .or_else(|| std::env::var("DWARA_PID_FILE").ok())
                .filter(|s| !s.is_empty());
            let Some(path) = path else {
                eprintln!(
                    "upgrade: no PID given. Pass --pid <N> or --pid-file <path>, \
                     or start the gateway with DWARA_PID_FILE set."
                );
                return 1;
            };
            let text = match std::fs::read_to_string(&path) {
                Ok(t) => t,
                Err(e) => {
                    eprintln!("upgrade: cannot read PID file {path}: {e}");
                    return 1;
                }
            };
            match text.trim().parse::<u32>() {
                Ok(p) => p,
                Err(_) => {
                    eprintln!("upgrade: PID file {path} does not contain a valid PID");
                    return 1;
                }
            }
        }
    };
    // libc::kill is the portable Unix primitive (no shell-out to `kill`).
    // SIGUSR2 (12) is the upgrade trigger the gateway's signal handler
    // listens for alongside SIGHUP/SIGTERM/SIGINT.
    let rc = unsafe { libc::kill(pid as i32, libc::SIGUSR2) };
    if rc == 0 {
        println!(
            "upgrade: SIGUSR2 sent to PID {pid}; the gateway will spawn a new \
             process, drain, and exit. Watch the logs to confirm the hand-off."
        );
        0
    } else {
        let err = std::io::Error::last_os_error();
        eprintln!("upgrade: failed to signal PID {pid}: {err}");
        1
    }
}

/// DW-065: `dwara tf` subcommand dispatch. The tf tool exports/imports
/// Terraform-compatible JSON state and generates HCL, performing
/// plan/apply round-trips directly over the admin API. The HTTP client
/// uses hyper (plaintext loopback — the dev admin is the primary
/// target; mTLS is a documented follow-up via the same flags the admin
/// client uses).
fn run_tf(kind: TfKind) -> i32 {
    let rt = match tokio::runtime::Runtime::new() {
        Ok(rt) => rt,
        Err(e) => {
            eprintln!("tf: cannot start tokio runtime: {e}");
            return 1;
        }
    };
    match kind {
        TfKind::Export {
            admin,
            ca,
            client_cert,
            client_key,
            out_state,
            out_hcl,
        } => match rt.block_on(dwara_cli::tf::export(
            &admin,
            ca.as_deref(),
            client_cert.as_deref(),
            client_key.as_deref(),
        )) {
            Ok((state_json, hcl)) => {
                if let Err(e) = write_atomic(&out_state, &state_json) {
                    eprintln!("tf export: cannot write state: {e}");
                    return 1;
                }
                if let Err(e) = write_atomic(&out_hcl, &hcl) {
                    eprintln!("tf export: cannot write HCL: {e}");
                    return 1;
                }
                println!("tf export: wrote {out_state} and {out_hcl}");
                0
            }
            Err(e) => {
                eprintln!("tf export: {e}");
                1
            }
        },
        TfKind::Plan {
            admin,
            state,
            ca: _,
        } => match rt.block_on(dwara_cli::tf::plan(&admin, &state)) {
            Ok((text, has_diff)) => {
                print!("{text}");
                if has_diff {
                    1
                } else {
                    0
                }
            }
            Err(e) => {
                eprintln!("tf plan: {e}");
                1
            }
        },
        TfKind::Apply {
            admin,
            state,
            config,
            ca: _,
        } => {
            let config_yaml = if let Some(path) = &config {
                match read(path) {
                    Ok(text) => Some(text),
                    Err(e) => {
                        eprintln!("tf apply: {e}");
                        return 1;
                    }
                }
            } else {
                None
            };
            match rt.block_on(dwara_cli::tf::apply(&admin, &state, config_yaml.as_deref())) {
                Ok(resp) => {
                    println!("tf apply: {resp}");
                    0
                }
                Err(e) => {
                    eprintln!("tf apply: {e}");
                    1
                }
            }
        }
        TfKind::ApplyCrud {
            admin,
            state,
            ca: _,
        } => match rt.block_on(dwara_cli::tf::apply_crud(&admin, &state)) {
            Ok(summary) => {
                println!("tf apply-crud: {summary}");
                0
            }
            Err(e) => {
                eprintln!("tf apply-crud: {e}");
                1
            }
        },
    }
}

/// DW-064: generate the upstream Gateway API conformance report YAML.
/// Based on the features the translator actually supports (see
/// `dwara_core::k8s_gateway::supported_features` / `skipped_features`).
fn run_conformance_report(output: Option<String>) -> i32 {
    let report = dwara_cli::k8s_conformance::generate_report();
    let yaml = match serde_yaml_ng::to_string(&report) {
        Ok(y) => y,
        Err(e) => {
            eprintln!("cannot serialize conformance report: {e}");
            return 1;
        }
    };
    match output {
        Some(path) => match write_atomic(&path, &yaml) {
            Ok(()) => {
                println!("conformance report written to {path}");
                0
            }
            Err(e) => {
                eprintln!("{e}");
                1
            }
        },
        None => {
            print!("{yaml}");
            0
        }
    }
}

/// DW-102: `dwara replay` — re-run the gateway's decision path for
/// recorded requests against a candidate config and emit a per-request
/// diff. Exit 0 if no diffs, 1 if diffs found, 2 on load error.
fn run_replay_cmd(
    recording: Option<String>,
    from: Option<i64>,
    to: Option<i64>,
    analytics_db: Option<String>,
    baseline: Option<String>,
    config: String,
) -> i32 {
    let candidate_text = match read(&config) {
        Ok(t) => t,
        Err(e) => {
            eprintln!("{e}");
            return 2;
        }
    };
    // Two modes: --recording (a JSON file with baseline + requests) or
    // --from/--to (read from the analytics store directly). The
    // --recording mode is the primary path; --from/--to reads raw rows
    // from the analytics SQLite database and builds a recording
    // in-memory.
    let recording_text = if let Some(path) = recording {
        match read(&path) {
            Ok(t) => t,
            Err(e) => {
                eprintln!("{e}");
                return 2;
            }
        }
    } else if let (Some(from_ms), Some(to_ms), Some(db_path), Some(baseline_path)) =
        (from, to, analytics_db, baseline)
    {
        let baseline_text = match read(&baseline_path) {
            Ok(t) => t,
            Err(e) => {
                eprintln!("{e}");
                return 2;
            }
        };
        match build_recording_from_store(&db_path, from_ms, to_ms, &baseline_text) {
            Ok(t) => t,
            Err(e) => {
                eprintln!("cannot read analytics store: {e}");
                return 2;
            }
        }
    } else {
        eprintln!(
            "replay: provide --recording <path>, or --from/--to with --analytics-db and --baseline"
        );
        return 2;
    };
    match dwara_cli::replay::run_replay(&recording_text, &candidate_text) {
        Ok(report) => {
            print!("{}", report.render());
            if report.diff_count == 0 {
                0
            } else {
                1
            }
        }
        Err(e) => {
            eprintln!("replay: {e}");
            2
        }
    }
}

/// Build a recording JSON from the analytics store: read raw rows in
/// the `[from_ms, to_ms]` window and serialize them with the baseline
/// config. Returns the recording JSON text.
fn build_recording_from_store(
    db_path: &str,
    from_ms: i64,
    to_ms: i64,
    baseline_config: &str,
) -> Result<String, String> {
    use dwara_cli::replay::{RecordedRequest, Recording};
    let conn = rusqlite::Connection::open(db_path)
        .map_err(|e| format!("cannot open analytics database {db_path}: {e}"))?;
    // Ensure the schema is migrated (the store may have been written by
    // an older build; the v10 columns are nullable so a pre-v10 DB
    // still reads — the ALTER TABLE in migrate() adds them).
    dwara_core::analytics::schema::migrate(&conn)
        .map_err(|e| format!("cannot migrate analytics database: {e}"))?;
    let mut stmt = conn
        .prepare(
            "SELECT method, route, consumer, ts_ms, request_headers_redacted, auth_identity
             FROM raw
             WHERE ts_ms >= ?1 AND ts_ms <= ?2
             ORDER BY ts_ms",
        )
        .map_err(|e| format!("cannot query raw table: {e}"))?;
    let rows = stmt
        .query_map(rusqlite::params![from_ms, to_ms], |r| {
            let method: String = r.get(0)?;
            let path: String = r.get(1)?;
            let _consumer: String = r.get(2)?;
            let ts_ms: i64 = r.get(3)?;
            let headers_json: Option<String> = r.get(4)?;
            let auth_identity: Option<String> = r.get(5)?;
            let headers: Vec<(String, String)> = headers_json
                .as_deref()
                .and_then(|s| serde_json::from_str(s).ok())
                .unwrap_or_default();
            Ok(RecordedRequest {
                method,
                path,
                headers,
                auth_identity,
                timestamp_ms: ts_ms,
            })
        })
        .map_err(|e| format!("cannot query raw rows: {e}"))?;
    let mut requests = Vec::new();
    for row in rows {
        let req = row.map_err(|e| format!("cannot read raw row: {e}"))?;
        requests.push(req);
    }
    let recording = Recording {
        baseline_config: baseline_config.to_string(),
        requests,
    };
    serde_json::to_string(&recording).map_err(|e| format!("cannot serialize recording: {e}"))
}

/// USA-02 (#179): `dwara status` — one-shot snapshot of the running
/// gateway over the admin API. Exit 0 on success, 1 on error.
fn run_status(admin: Option<String>) -> i32 {
    let admin_url = dwara_cli::status::resolve_admin(admin.as_deref());
    let rt = match tokio::runtime::Runtime::new() {
        Ok(rt) => rt,
        Err(e) => {
            eprintln!("status: cannot start tokio runtime: {e}");
            return 1;
        }
    };
    match rt.block_on(dwara_cli::status::status(&admin_url)) {
        Ok(out) => {
            print!("{out}");
            0
        }
        Err(e) => {
            eprintln!("status: {e}");
            1
        }
    }
}

/// USA-02 (#179): `dwara top` — live, refreshing view of upstream
/// load-balancer state. Runs until interrupted (Ctrl-C). Exit 0 on
/// interrupt, 1 on error.
fn run_top(admin: Option<String>, interval: u64) -> i32 {
    let admin_url = dwara_cli::status::resolve_admin(admin.as_deref());
    let rt = match tokio::runtime::Runtime::new() {
        Ok(rt) => rt,
        Err(e) => {
            eprintln!("top: cannot start tokio runtime: {e}");
            return 1;
        }
    };
    match rt.block_on(dwara_cli::status::top(&admin_url, interval)) {
        Ok(()) => 0,
        Err(e) => {
            eprintln!("top: {e}");
            1
        }
    }
}

/// USA-02 (#179): `dwara completions <shell>` — generate a shell
/// completion script for the dwara-cli command model and print it to
/// stdout. Install per the clap_complete docs, e.g. for bash:
/// `dwara completions bash > /etc/bash_completion.d/dwara`.
fn run_completions(shell: CompletionShell) -> i32 {
    use clap::CommandFactory as _;
    let cmd = Cli::command();
    let shell = match shell {
        CompletionShell::Bash => clap_complete::Shell::Bash,
        CompletionShell::Zsh => clap_complete::Shell::Zsh,
        CompletionShell::Fish => clap_complete::Shell::Fish,
        CompletionShell::Powershell => clap_complete::Shell::PowerShell,
    };
    let bin = "dwara-cli";
    clap_complete::generate(shell, &mut cmd.clone(), bin, &mut std::io::stdout());
    0
}
