apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dwara-controller
  namespace: dwara-system
  labels:
    app.kubernetes.io/name: dwara
    app.kubernetes.io/component: gateway
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: dwara
      app.kubernetes.io/component: controller
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8443
