apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dwara-controller
  namespace: dwara-system
  labels:
    app.kubernetes.io/name: dwara
    app.kubernetes.io/component: gateway
    release: kube-prom
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dwara
      app.kubernetes.io/component: gateway
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
