#!/bin/bash
# publish.sh -- the entitlement publisher (use case 1, Option A's
# "publishing loop").
#
# Pulls the current allow-list from the entitlement microservice,
# writes it into the GENERATED plugins-config include (the plugin's
# config snapshot), and atomically replaces the main config file with
# its own (identical) bytes so the gateway's file watcher fires. The
# reload path resolves the include, the compiled config changes, and a
# new generation publishes -- while the plugin module's checksum is
# unchanged, so the loaded module and its health state are kept; only
# the config (and thus on_configure) refreshes.
#
# The main-config rewrite is the documented "touch the main config"
# step: the watcher fires on write/rename events for the config file's
# name, and a plain mtime touch is deliberately ignored (metadata-only
# churn). Replacing the file with identical content is enough -- the
# file-watch no-op check compares the COMPILED config, which changed
# through the include.
#
# When the gateway's PID is given (third arg) the publisher ALSO sends
# SIGHUP: a forced, deterministic reload. File-watch events depend on
# the platform's filesystem event semantics (on macOS FSEvents the
# rename event does not always carry the destination file name, so the
# watcher's name filter can miss it); SIGHUP always re-reads,
# re-validates, and re-publishes. Belt and braces: either trigger
# alone is correct, together they are reliable everywhere.
#
# Usage: publish.sh <config-dir> [entitlement-url] [gateway-pid]
#   <config-dir>       directory holding dwara.yaml and plugins-config/
#   [entitlement-url]  defaults to http://127.0.0.1:18203
#   [gateway-pid]      when set, SIGHUP the gateway after publishing
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="${1:?usage: publish.sh <config-dir> [entitlement-url] [gateway-pid]}"
ENT_URL="${2:-http://127.0.0.1:18203}"
GW_PID="${3:-}"
WASM="$SCRIPT_DIR/../plugin/target/wasm32-wasip1/release/v2_migrator.wasm"

CONFIG="$CONFIG_DIR/dwara.yaml"
[ -f "$CONFIG" ] || { echo "publish.sh: no dwara.yaml in $CONFIG_DIR" >&2; exit 1; }
[ -f "$WASM" ] || { echo "publish.sh: plugin artifact missing (build it first): $WASM" >&2; exit 1; }
mkdir -p "$CONFIG_DIR/plugins-config"

# 1) Pull the entitlement service's current allow-list (fail loudly:
#    never publish a guessed list).
users_json=$(curl -sf "$ENT_URL/entitlements") || {
  echo "publish.sh: entitlement service unreachable at $ENT_URL" >&2
  exit 1
}

# 2) Render the generated include. python3 formats the JSON allow-list
#    (correct quoting for any user id) into the plugin's config block.
python3 - "$CONFIG_DIR/plugins-config/v2-migrator.yaml" "$WASM" "$users_json" <<'PY'
import json
import sys

out_path, wasm, users_json = sys.argv[1], sys.argv[2], sys.argv[3]
state = json.loads(users_json)
config = json.dumps(
    {"from": "/v1/", "to": "/v2/", "allowed_users": state["allowed_users"]},
    separators=(", ", ": "),
)
include = "\n".join(
    [
        "# GENERATED by services/publish.sh -- do not edit by hand.",
        "# Source of truth: the entitlement microservice allow-list",
        f"# (revision {state.get('revision', '?')}). Regenerated on every publish.",
        "plugins:",
        "  - name: v2-migrator",
        f"    wasm: {wasm}",
        "    phases:",
        "      - request_headers",
        "    limits: { fuel: 1000000, memory_mb: 32 }",
        "    config: |",
        f"      {config}",
        "",
    ]
)
with open(out_path, "w") as fh:
    fh.write(include)
print(f"publish.sh: wrote {out_path} (allowed_users={state['allowed_users']})")
PY

# 3) Touch the main config: an atomic same-name replace. This is what
#    the file watcher sees; content is unchanged by design (the
#    include carries the change).
tmp="$CONFIG_DIR/.dwara.yaml.publishing"
cp "$CONFIG" "$tmp"
mv "$tmp" "$CONFIG"
if [ -n "$GW_PID" ]; then
  kill -HUP "$GW_PID"
  echo "publish.sh: main config rewritten + SIGHUP sent to gateway pid $GW_PID"
else
  echo "publish.sh: main config rewritten (file-watch reload trigger)"
fi
